name: feather_track_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_database: ^10.4.10
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  responsive_framework: ^1.4.0
  pdf: ^3.11.3
  printing: ^5.13.1
  fl_chart: ^0.71.0
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  file_picker: ^8.0.7
  rxdart: ^0.27.7
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
